// eslint-disable-next-line no-unused-expressions
[
  {
    bhk: "2 BHK 3 BHK 3+ BHK ",
    brokerage: null,
    createdby: "lubhan",
    createddate: "2022-09-01",
    deleteby: null,
    deletedate: null,
    flatno: null,
    furnishedstatus: "unfurnished",
    isdeleted: false,
    leadgenerationdate: "2021-09-10",
    leadid: "0a38bf7e-7332-0aec-32aa-6197c76a64c3",
    leadname: "Sakshi Singh",
    location: "Viman Nagar",
    mobile: 7020644020,
    poss: null,
    price: "1.1 Cr-1.76 Cr",
    societyname: "Shubh Gateway",
    sqft: null,
    updatedby: "lubhan",
    updateddate: null,
    wingno: null,
  },
  {
    bhk: "2 BHK 3 BHK 3+ BHK ",
    brokerage: null,
    createdby: "lubhan",
    createddate: "2022-09-01",
    deleteby: null,
    deletedate: null,
    flatno: null,
    furnishedstatus: "unfurnished",
    isdeleted: false,
    leadgenerationdate: "2021-09-10",
    leadid: "0a38bf7e-7332-0aec-32aa-6197c76a64c3",
    leadname: "Sakshi Singh",
    location: "Viman Nagar",
    mobile: 7020644020,
    poss: null,
    price: "1.1 Cr-1.76 Cr",
    societyname: "Shubh Gateway",
    sqft: null,
    updatedby: "lubhan",
    updateddate: null,
    wingno: null,
  },
  {
    bhk: "1 BHK 2 BHK 2 BHK ",
    brokerage: null,
    createdby: "lubhan",
    createddate: "2022-09-01",
    deleteby: null,
    deletedate: null,
    flatno: null,
    furnishedstatus: "unfurnished",
    isdeleted: false,
    leadgenerationdate: "2021-10-10",
    leadid: "ce0cb7ed-9b5a-681a-419d-bf11e6a25479",
    leadname: "Swapnil Chaudhari",
    location: "Dhanori",
    mobile: 7028028138,
    poss: null,
    price: "36.44 L-68.71 L",
    societyname: "Goel Ganga Newtown Phase 2",
    sqft: null,
    updatedby: "lubhan",
    updateddate: null,
    wingno: null,
  },
  {
    bhk: "1 RK 2 BHK 3 BHK ",
    brokerage: null,
    createdby: "lubhan",
    createddate: "2022-09-01",
    deleteby: null,
    deletedate: null,
    flatno: null,
    furnishedstatus: "unfurnished",
    isdeleted: false,
    leadgenerationdate: "2021-10-10",
    leadid: "d01c4354-abfb-8c8a-93d6-3dcdc355fe3c",
    leadname: "Deepali",
    location: "Kharadi",
    mobile: 7972937181,
    poss: null,
    price: "33.0 L-1.18 Cr",
    societyname: "Geras World of Joy L",
    sqft: null,
    updatedby: "lubhan",
    updateddate: null,
    wingno: null,
  },
  {
    bhk: "1 RK 2 BHK 3 BHK ",
    brokerage: null,
    createdby: "lubhan",
    createddate: "2022-09-01",
    deleteby: null,
    deletedate: null,
    flatno: null,
    furnishedstatus: "unfurnished",
    isdeleted: false,
    leadgenerationdate: "2021-10-10",
    leadid: "4d10af14-4ca5-7821-99aa-dcd462a98e9d",
    leadname: "Yogesh",
    location: "Kharadi",
    mobile: 9373251107,
    poss: null,
    price: "33.0 L-1.18 Cr",
    societyname: "Geras World of Joy L",
    sqft: null,
    updatedby: "lubhan",
    updateddate: null,
    wingno: null,
  },
];
